changelog:
  categories:
    - title: "Neue Funktionen"
      types:
        - feat
    - title: "Bug Fixes"
      types:
        - fix
    - title: "Änderungen"
      types:
        - chore
        - refactor
        - perf
        - docs
        - ci
        - style
        - test
    - title: "Dependency Updates"
      types:
        - build
    - title: "Weitere Änderungen"
