language: node_js
node_js:
  - 14
before_install:
  - rm yarn.lock
script:
  - yarn install
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: "hkfIcGFEsdI4KdeSqY1vw9iXfZakAiOA9AOuWta+SNzu5T8TeShjKSH78wuqwjSRI0ni6kjeJpbL2S4HmbEVxkcz7WeK2SbNc+mGMy1/1EvZKHjVPWPCU+sADWGgCOSHpWF9khGKJSQM0pxmxVbG45WtAwevOKy8GQUNZESjMOL4huNOHVWJTl+N610O0/LJPkS4MW98WxlNldnZoN1o8KEg8K/cBNF1BIxzLZXDldo7Jdo4j6HiAcEMDPgWHWAymqe+8bXgO6CeegGjV9326SxvUthQ1ZBBw/ZnJNGD9kSG7h/uY5dExYhqdjgAeWg76UeSsQ0+J/KCqk8Fgf1tsJSowB58Jc5T5Ax/TRLq6KUpAsXMFN3z+G7f9NXXdRg9Dv1hT/s1/FcnzG8xP2OJnjAxMsSYwJ4Hartwj/0euJCGAwHKoZEMKHl1nwA3II+N1PhTdf9y1YyKLd9ctWXXLptx6kdjB+d+dPMa9BAxYXFAJWIyd7tJ9Q1lFtRTEQevz+jVKqonfBd3NClz3slu5szyQmn7pIkz8yyosuAQQ15mGzn70c1yNRoQsE6ptbL+3hIFuN6uZd2LNblB94FAZdBkRs15eiOx+LBXuqkcpWaYIaZinaxbz5rulhAFXCi+0OOt+H2sKx6vbQGTWfMtCDHNByLxislZT1tJ8mwARls="
  app: cevi-buchs-rohr-aarau-webpage
  on:
    repo:  patrickuhlmann/cevi-buchs-rohr-aarau-website 
