language: node_js
node_js:
- 14
before_install:
- rm yarn.lock
script:
- yarn install
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: KkapHQ+GpWvi2ZD/gyeP4iD6vknQ1w943N3jKQpxfxd34UXP+kpOrMGuz4gTxk79LdMLDF3ZJgGpG2XYMgh9LGrezZpLj8PuksVg/hM4ulk+hEPlK4hbn24OB071t6f1mus3u9H0U9Mv7xx64LG6h0jtxsD8qhQM6dLg703GZn/PglTJ1xToGTbHdgWV1/W7INU2nKm41HguH8ew7IKN/pKems7GBpRgFwrsY4qNY18Sx1iyEdPPSOU8aQDp6hTTaMQxZmCKZWqU4XMNIjcHUR8iJR0hs7J/ma3bx6TfFZwUzkiO4MpDh0M8FZmpLsNHOZ18xQtyXXiiumdZOnv+oHS64TamyuSpioTgz8+TbpmIBL41Kj8lx8PTt8EiNoKeXqk3yeuHkJU/hpE3Mo6zK6K0Ik482KV1Q9RVLfcxhdwED0hwYfykt7kV5UDnblTRKEG3HVDMI/1VBu80WMvnQl5hWB1TVPpX+4B4oy+Btp2xDrLMf2MYqg8X+s0kbbThMkjpJ3Fe1tEarb262If6nE7T9FKB+3agaQSOfS/3gRRxOo98dHNWyYNpWN9xZc/3+jMdFo3vPR64AlFvAGSqhaGZUirCkxWH3qPk7S2pD2WgdVRMgPUR9FFkz3swGUhXoFsxnIUfip4u+9fXijfKOI6qlgQR92IcYDhbHmuneVI=
  app: cevi-buchs-rohr-aarau-webpage
  on:
    repo: patrickuhlmann/cevi-buchs-rohr-aarau-website
