name: Deploy on Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [build, analyze, sonarcloud ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cevi-buchs-rohr-aarau-webpage"
          heroku_email: "heroku@uhlme.ch"
          usedocker: true
