name: Main

on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 1 * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
  build_and_test:
    name: "Build and Test"
    needs: analyze
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: "Install Dependencies"
      run: yarn --frozen-lockfile

    - name: "Build"
      run: yarn run build
      
    - name: Archive dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist
          !dist/report.html
          
    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: webpack report
        path: dist/report.html

    - name: "Unit Tests"
      run: yarn test:unit
      
    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: unit test coverage report
        path: coverage
      
  sonarcloud:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: "Deploy to Heroku"
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cevi-buchs-rohr-aarau-webpage"
          heroku_email: "heroku@uhlme.ch"
          usedocker: true
