on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
  schedule:
    - cron: '21 18 * * 3'
    
name: Sonarcloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
